import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { AuthProvider } from "@/components/providers/AuthProvider"

const gilroyLight = localFont({
  src: "./fonts/Gilroy-Light.otf",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${gilroyLight.className} flex min-h-screen items-center justify-center bg-gradient-to-b from-purple-100 to-purple-50`}
        >
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  )
}
